# kalman covariances
kalman_cov:
  filter_init_var_x: 0.5
  filter_init_var_y: 0.5
  sys_var_x: 0.1
  sys_var_y: 0.1

# allowed distance between objects (they get merged if lower)
dist_threshold: 0.9

# remove this amount of trust in each prediction step
# value should depend on input message frequency and trust
remove_trust: 0.08

# moving average filter length for velocities (prediction)
mov_avg_size: 20
